samples_file: "path/to/WK-3860_samples.csv"

protein_reference_file: "path/to/protein_references/BOLD_output_mge_fetch_sum_out.csv"

output_dir: "path/to/MGE-out"

genes:
  - cox1
  



#r_params:
#  - 1 default of MGE
#  - 0.7

#s_params:
#  - 100 defualt of MGE
#  - 70

