samples_file: "/home/danip3/MitoGeneExtractor-main/BGE-test/mge_test_snakemake/WK-3860_samples.csv"

output_dir: "/gpfs/nhmfsa/bulk/share/data/mbl/share/scratch/MGE"

genes:
  - cox1
  

r_params:
  - 1 # default of MGE
#  - 0.8
#  - 1.5


s_params:
  - 100 # defualt of MGE
#  - 70
#  - 50
