#Path to samples.csv
samples_file: "./BGE_test_samples.csv"

#path to protein_references.csv
protein_reference_file: "./protein_references/gene_fetch_BGE_test_data.csv"

#path to output directory. Will make final dir if it does not exist already.
output_dir: "./MGE-out"

#Gene(s) of interest
genes:
  - cox1

#Exonerate relative score threshold parameter
r:
  - 1 
  - 1.3
  - 1.5

#Exonerate minimum score threshold parameter
s:
  - 100
  - 50
  
#Run identifier - can be called anything
run_name: "mge_standard_alt-params"
