samples_file: "./BGE_test_samples.csv"

protein_reference_file: "./gene_fetch_BGE_test_data.csv"

output_dir: "/gpfs/nhmfsa/bulk/share/data/mbl/share/scratch/MGE"

genes:
  - cox1
  



#r_params:
#  - 1 default of MGE
#  - 0.8
#  - 1.5

#s_params:
#  - 100 default of MGE
#  - 80
#  - 50
