#Run identifier - can be called anything
run_name: "mge_standard_r1s100"

#Absolute path to MGE installation
mge_path: "PATH/TO/MitoGeneExtractor-v1.9.5"

#Path to samples.csv
samples_file: "./BGE_test_samples.csv"

#path to protein_references.csv
protein_reference_file: "./protein_references/gene_fetch_BGE_test_data.csv"

#path to output directory. Will make final dir if it does not exist already.
output_dir: "./results/mge_standard_r1s100"

#Gene(s) of interest
genes:
  - cox1

#Exonerate relative score threshold parameter
r:
  - 1 
#  - 1.3
#  - 1.5

#Exonerate minimum score threshold parameter
s:
  - 100
#  - 50
  

